"use client";

import React, { useState, useEffect } from "react";

// AOS
import AOS from "aos";
import "aos/dist/aos.css";

// font
const inter = Inter({ subsets: ["latin"] });
import { Inter } from "next/font/google";

// style
import "@/styles/destyles.css";
import "@/styles/styles.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  React.useEffect(() => {
    AOS.init({
      once: true,
      duration: 1000,
    });
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

