"use client";

import React, { useEffect } from "react";
import { usePathname } from "next/navigation";

// aos
import AOS from "aos";
import "aos/dist/aos.css";

// component
import Header from "@/components/Header/index.js";
import Footer from "@/components/Footer/index.js";

// style
import "@/styles/destyles.css";
import "@/styles/global.scss";
import "@/styles/styles.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    AOS.init({
      once: true,
      duration: 1000,
    });
  }, []);

  const pathname = usePathname();

  return (
    <html>
      <body>
        <Header isTopPage={pathname === "/"} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
